# Supported hooks
# - https://pre-commit.com/hooks.html
# - https://github.com/pre-commit/pre-commit-hooks/blob/main/README.md
default_stages: [commit, push]
default_language_version:
  python: python3.11
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-merge-conflict
      - id: requirements-txt-fixer
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-ast
      # - id: check-yaml # fails on template yamls unfortunately :(
  - repo: https://github.com/PyCQA/autoflake
    # Removes unused imports and variables
    rev: v2.1.1
    hooks:
      - id: autoflake

        args:
          [--in-place, --remove-unused-variables, --remove-all-unused-import]
  - repo: https://github.com/ambv/black
    rev: 23.3.0
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        files: \.(js|ts|jsx|tsx|css|less|html|json|markdown|md|yaml|yml)$
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
