[tool.poetry]
name = "peertix-alfred-ai"
version = "0.1.0"
description = ""
authors = ["Medveczky Krisztián <krisz.medveczky@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11,<3.13"
crewai = "^0.76.2"
crewai-tools = "^0.13.2"
flytekit = "^1.13.13"
langchain-google-genai = "^2.0.6"
jinja2 = "^3.1.4"
firebase-admin = "^6.6.0"


[tool.poetry.scripts]
crew = "peertix_alfred_ai.main:main"
artist-research = "peertix_alfred_ai.main:run_artist_research_crew"
marketing-research = "peertix_alfred_ai.main:run_instagram_research_crew"
sport-research = "peertix_alfred_ai.main:run_sport_research_crew"
topic-classifier = "peertix_alfred_ai.main:run_topic_classifier_crew"

[tool.poetry.group.dev.dependencies]
pre-commit = "^4.0.1"

[tool.black]
line-length = 118
target-version = ['py311']
include = '\.pyi?$'
# 'extend-exclude' excludes files or directories in addition to the defaults
extend-exclude = '''
# A regex preceded with ^/ will apply only to files and directories
# in the root of the project.
(
  ^/foo.py    # exclude a file named foo.py in the root of the project
  | .*_pb2.py  # exclude autogenerated Protocol Buffer files anywhere in the project
)
'''


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
